baseURL = "https://NotPhiQuadro.github.io/personal-website"
title = "Giacomo Santato"
theme = "PaperMod"
languageCode = "en-us"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

    [languages.en.params]
      author = "Giacomo Santato"
      description = "Cryptography PhD student and CTF player"
      showSocialIcons = true

[menu]
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "CTF"
    url = "/ctf/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["\\[", "\\]"], ["$$", "$$"]]
          inline = [["\\(", "\\)"]]

[outputs]
section = ["HTML"]
[params]
  mainSections = []  
  disableMetadata = true
  [params.assets]
  favicon = "favicon.png" 

